--
-- Dataset containing shorten urls and redirection.
--

-- =================================================================================================
-- SHORTEN URLS

--drop table shorten_url if exists;
create table shorten_url (id bigint generated by default as identity, code varchar(255), created timestamp, url varchar(255), primary key (id));
